
---
title: "Main script Erik Vectra analysis"
output:
  html_document:
    toc: yes
---


```{r load_package}
source('spatstat_vectra.R')


base_path <- '../Exported data tables/' # Working for Yongsoo
base_path <- path.expand('~/Studie/Thesis - Local/Data Marit voor Erik Bosch/Erik Bosch/Data complete phenotyping') # working for Erik
paths_to_seg <- list_cell_seg_files(base_path)
cat("There are", length(paths_to_seg), "segmentation paths currently loaded")


phenotype_complete = c("CD163+PDL1-","CD163+PDL1+",
                       "CD3+CD8-PD1-", "CD3+CD8-PD1+", "CD3+CD8+PD1-", "CD3+CD8+PD1+",
                       "Other","Other PDL1+",
                       "PAX5+PDL1-", "PAX5+PDL1+",
                       "")

color_complete = list("magenta", "brown",
                   "red", "blue", "green", "yellow",
                   "gray", "pink",
                   "orange", "cyan",
                   "gray")
names(color_complete) = phenotype_complete

fig.prefix.complete = './complete'

r_vec = c(20,100)


phenotype_simple = list(Macrophage = c("CD163+PDL1-","CD163+PDL1+"),
                      Tcells = c("CD3+CD8-PD1-", "CD3+CD8-PD1+", "CD3+CD8+PD1-", "CD3+CD8+PD1+"),
                      Tumors = c("PAX5+PDL1-", "PAX5+PDL1+"),
                      Others = c("Other", "Other PDL1+")
                      )

color_simple = c(Macrophage = "magenta", Tcells = "red", Tumors = "orange", Others = "gray")

fig.prefix.simple = './simple'
```


```{r HO105_extreme,fig.width=8, fig.height=8} 
source('spatstat_vectra.R')

extreme = file.path(base_path, c(
		'HO105-194_[16067,37856]_cell_seg_data.txt', # PD-L1 positive cluster + Tumor cluster
		'HO105-194_[15564,37856]_cell_seg_data.txt', # PD-L1 positive cluster + Tumor cluster
		'HO105-194_[16029,38205]_cell_seg_data.txt' # not clustered
	))
D = file.path(base_path, c(
    'HO105-006_[9554,40992]_cell_seg_data.txt',  # complete and simple: no component (not in marits file) 1
    'HO105-006_[10041,41957]_cell_seg_data.txt', # complete and simple: no component (not in marits file) 2
		'HO105-140_[16281,41985]_cell_seg_data.txt', # complete: Fest spacing  3 inside alltypes(..,fun=J) small counts 5,1
		'HO105-083_[20512,33844]_cell_seg_data.txt', # simple: (maybe counts) 4 inside alltypes no Tcells solved
		'HO105-083_[18166,32820]_cell_seg_data.txt', # simple: (maybe counts) 5 inside alltypes no Tcells solved
		'HO105-097_[9517,43652]_cell_seg_data.txt',  # simple: (maybe counts) 6 inside alltypes no Tcells solved
		'HO105-097_[8938,43999]_cell_seg_data.txt',  # simple: (maybe counts) 7 inside alltypes no Tcells solved
		'HO105-097_[11295,45384]_cell_seg_data.txt', # simple: (maybe counts) 8 inside alltypes no Tcells solved
		'HO105-121_[8016,47627]_cell_seg_data.txt',  # complete: Fest spacing 9 inside alltypes(..,fun=J) small counts 5,2
		'HO105-083_[20684,34346]_cell_seg_data.txt', # simple: (maybe counts) 10 inside alltypes no Tcells solved
		'HO105-083_[14332,34366]_cell_seg_data.txt', # simple: (maybe counts) 11 inside alltypes no Tcells solved
		'HO105-083_[14941,33993]_cell_seg_data.txt', # simple: (maybe counts) 12 inside alltypes no Tcells solved
		'HO105-083_[18456,34691]_cell_seg_data.txt', # simple: (maybe counts) 13 inside alltypes no Tcells solved
		'HO105-083_[15677,36542]_cell_seg_data.txt', # simple: (maybe counts) 14 inside alltypes no Tcells solved
		'HO105-083_[15726,34331]_cell_seg_data.txt', # simple: (maybe counts) 15 inside alltypes no Tcells solved
		'HO105-095_[15101,39877]_cell_seg_data.txt', # complete: Fest spacing 16 inside alltypes(..,fun=J) small counts 5,1 maybe area is to thin?
		'HO105-083_[16066,33773]_cell_seg_data.txt', # simple: (maybe counts) 17 inside alltypes no Tcells solved
		'HO105-083_[16367,35783]_cell_seg_data.txt'  # simple: (maybe counts) 18 inside alltypes no Tcells solved
	))
# extreme = D
# Plot variables

plotter_sample = F
plotter_quadrat = F
plotter_alltypes = T

plotter = list(plotter_sample, plotter_quadrat, plotter_alltypes)

# Select spatial statistics, or NULL then all inbuild spatial statistics are selected
selected_spatstat_statistics = NULL

# debug

# extreme = D[8]
# extreme = c(extreme[3],D[8])
samplename = gsub('_cell_seg_data.txt', '', tail(strsplit(extreme, '/')[[1]],1))
seg_path = extreme
PhenoOrder = phenotype_simple
ColsOrder = color_simple
XposCol = 'Cell X Position'
YposCol = 'Cell Y Position'
PhenoCol = 'Phenotype'
sample_name = samplename
plotter = plotter
fig.prefix = fig.prefix.simple
r_vec = r_vec
spatstat_statistics = selected_spatstat_statistics

outputs_auto = list()
for (file in extreme){
	cat('processing', file)
    
  samplename = gsub('_cell_seg_data.txt', '', tail(strsplit(file, '/')[[1]],1))
	outputs_auto[[samplename]] = do_analyse(seg_path = file, PhenoOrder = phenotype_simple, ColsOrder = color_simple,
                      XposCol = 'Cell X Position', YposCol = 'Cell Y Position', PhenoCol = 'Phenotype',
                      sample_name = samplename, plotter = plotter, fig.prefix = fig.prefix.simple,
                      r_vec = r_vec, spatstat_statistics = selected_spatstat_statistics)
}
saveRDS(outputs_auto, file = 'feature_matrix_output.RDS')
M = feature_extract(outputs = outputs_auto)
write.csv(x = M,file = file.path(fig.prefix.simple, 'feature_matrix.csv'))
```


```{r marit HO105 image check  all via import, fig.width=8, fig.height=8}
source('spatstat_vectra.R')
library('readxl')


#### Preprocessing ####
# Define path for all data
base_path <- '../Exported data tables/' # Working for Yongsoo
# base_path <- 'C:/Users/erikb/Documents/Thesis - Local/Data Marit voor Erik Bosch/Erik Bosch/Data complete phenotyping' # working for Erik
base_path = path.expand("~/Studie/Thesis - Local/Data Marit voor Erik Bosch/Erik Bosch/Data complete phenotyping")

# define path for selected images by Marit
image_check_path = NULL # working for Yongsoo (CHANGE)
image_check_path <- 'C:/Users/erikb/Documents/Studie/Thesis - Local/spatstat_vectra/HO105 image check.xlsx' # working for Erik
image_check_path <- path.expand('~/Studie/Thesis - Local/spatstat_vectra/HO105 image check.xlsx') # working for Erik


# all_files_x_ = rownames(base_path, pattern =  'HO105-',full.names = TRUE)
# names_with_x_ = list.files(base_path, pattern =  'HO105-[0-9]+_[0-9]_',full.names = TRUE)
# 
# if (length(names_with_x_)>0){
#     new_names = str_replace_all(all_files_x_, pattern = '_[0-9]_', replacement = '\\_')
#     warning(paste('file names have been renamed in the current directory',getwd()))
#     rename_log = file.rename(all_files_x_, new_names)
# }





#### Read file for selected images by Marit ####
HO105_image_check <- read_excel(image_check_path)

HOnrs_unfil = HO105_image_check$`HO105 nr`
tumor_images_data_unfil = HO105_image_check$`Tumor images`
# get the MSI's through regex finding: open bracket->MSI numbers->comma->MSI numbers-> closed bracket
tumor_images_unfil = str_extract_all(tumor_images_data_unfil,'\\[[0-9]+,[0-9]+\\]')
# create filter to check for non empty content
non_empty = !sapply(tumor_images_unfil,is_empty)
# create filtered tumor_images and HOnrs
tumor_images = tumor_images_unfil[non_empty]
HOnrs = HOnrs_unfil[non_empty]
names(tumor_images) = HOnrs
# create string with paths to segmentation data and component data to analyse
sample_names_marit = lapply(seq_along(HOnrs),function(x) paste0(names(tumor_images)[x],'_',unlist(tumor_images[HOnrs][x])))
sample_names_marit_str = unlist(sample_names_marit)
length(sample_names_marit_str)


# #### check if the component data and segmentation data are one to one ####
# # # find all files of HO105
# # all_files = list.files(base_path, pattern =  'HO105-')
# 
# ## find all available component data of HO105
# available_comp_tif = list.files(base_path, pattern = '_component_data.tif')
# # find the sample names of all available component data
# available_comp = lapply(available_comp_tif, function(x) gsub('_component_data.tif','',x))
# available_comp_str = unlist(available_comp)
# length(available_comp_str)
# 
# ## find all available segmentation data of HO105
# available_seg_txt = list.files(base_path, pattern = '_cell_seg_data.txt')
# # find the sample names of the all available segmentation data
# available_seg = lapply(available_seg_txt, function(x) gsub('_cell_seg_data.txt','',x))
# available_seg_str = unlist(available_seg)
# length(available_seg_str)


# # take intersection to retrieve the matching names with the data from Marits file
# matching_names_marit = intersect(sample_names_marit_str,available_comp_str)
# length(matching_names_marit)
# 
# # take the difference to retrieve the sample names of the missing component data
# diff_available_comp = setdiff(sample_names_marit_str,available_comp_str)
# length(diff_available_comp)
# 
# #take set difference of names of actual available components and names of components of 
# diff_available_seg = setdiff(sample_names_marit_str,available_seg_str)
# length(diff_available_seg)




```

```{r clinical vs prediction data}
source('spatstat_vectra.R')

# import simplified matrix

feature_matrix_simple = readRDS(path.expand('~/Studie/Thesis - Local/feature_matrix_simple.RDS'))


#### renaming rownames in simplified matrix with '_1_', '_2_', '_3_' and '_4_' (replace with '_') ####
all_rownames = rownames(feature_matrix_simple)
all_rownames = str_replace_all(all_rownames, pattern = '\\_[0-9]\\_', replacement = '\\_')

rownames(feature_matrix_simple) = all_rownames


# match_indices = match(sample_names_marit_str,all_rownames)
# feature_matrix_simple_tumor = feature_matrix_simple[match_indices,]
# 
# saveRDS(feature_matrix_simple_tumor, file = 'feature_matrix_simple_tumor.RDS')
# stop('joe')


#### function statisticPerPatient: take the statistic (mean or median) over all the features for each patient ####

statisticPerPatient <- function(mat, statistic = 'mean', na.handler = 'complete_cases'){
  
  # browser()
  if (isTRUE(na.handler == 'complete_cases')){
    # cat('samplenames with missing values removed for analyse:', rownames(mat[!complete.cases(mat),]), '. if empty either 0 or 1 samplenames are removed')
    na.rm = FALSE # default setting
    mat = mat[complete.cases(mat),] # complete cases
  } else if (isTRUE(na.handler == 'ignore_na')){
    na.rm = TRUE
  } else {
    stop('input na.handler must be either complete_cases or ignore_na')
  }
  
  if (isFALSE(statistic %in% c('mean','median'))){
    stop('input statistic must be either mean or median')
  }
  
  samplenames = rownames(mat)
  prediction_statistics = colnames(mat)
  nrs = unique(str_remove_all(samplenames,pattern = '\\_\\[[0-9]+,[0-9]+\\]'))
  
  mat_allpatients = matrix(NA, nrow = length(nrs), ncol = length(prediction_statistics))
  rownames(mat_allpatients) = nrs
  colnames(mat_allpatients) = prediction_statistics
  # browser()
  for (patientnr in nrs){
    
    samplenames_patient = str_subset(samplenames, patientnr)
    if (isTRUE(length(samplenames_patient) == 1) ){
      mat_patient = t(as.matrix(mat[samplenames_patient,]))
    } else {
      mat_patient = mat[samplenames_patient,]
    }
    mat_allpatients[patientnr,] = apply(mat_patient, 2, statistic, na.rm = na.rm)
  }
  mat_allpatients[is.nan(mat_allpatients)] = NA
  
  return(mat_allpatients)
}


mat_simple_allpatients_complete_cases_mean = statisticPerPatient(feature_matrix_simple, statistic = 'mean', na.handler = 'complete_cases')
# apply(feature_matrix_simple,1,function(x) sum(is.na(x))) if all bigger than 0, then every sample has NA's in them, so no complete cases exist
mat_simple_allpatients_ignore_na_mean = statisticPerPatient(feature_matrix_simple, statistic = 'mean', na.handler = 'ignore_na')
# apply(mat_simple_allpatients_ignore_na_mean,1,function(x) sum(is.na(x))) NA's are not a problem in this setting

mat_simple_allpatients_complete_cases_median = statisticPerPatient(feature_matrix_simple, statistic = 'median', na.handler = 'complete_cases')
# apply(feature_matrix_simple,1,function(x) sum(is.na(x))) if all bigger than 0, then every sample has NA's in them, so no complete cases exist
mat_simple_allpatients_ignore_na_median = statisticPerPatient(feature_matrix_simple, statistic = 'median', na.handler = 'ignore_na') 



# #### finding the the widths for significance band of each feature per patient
# 
# feature_matrix_simple = M
# uni_stats = unique(str_subset(colnames(feature_matrix_simple), '_radius'))
# 
# 
# spats_unnorm = str_subset(uni_stats, 'Normalized',negate = TRUE)
# m = matrix(NA,nrow = length(rownames(feature_matrix_simple)), ncol = length(spats_unnorm))
# rownames(m) = rownames(feature_matrix_simple)
# colnames(m) = spats_unnorm
# 
# for (patient in rownames(feature_matrix_simple)){
#   for (stat in spats_unnorm){
#     unnorm = feature_matrix_simple[patient,stat]
#     nnorm = feature_matrix_simple[patient,paste0('Normalized_',stat)]
#     width_sign_band = unnorm/nnorm
#     m[patient,stat] = width_sign_band
#   }
# }
# 
# width_sign_band_min = apply(m,1,function(x) min(x,na.rm = TRUE))
# width_sign_band_max = apply(m,1,function(x) max(x,na.rm = TRUE))



# m = matrix(1:36,nrow = 6)
# rownames(m) = list('HO105-097_[9517,43652]', 'HO105-097_[8938,43999]', 'HO105-097_[11295,45384]', 'HO105-121_[8016,47627]', 'HO105-083_[20684,34346]', 'HO105-083_[14332,34366]')
# colnames(m) = letters[1:6]
# m[4] = NA
# mat = m

# NaN -> apply(matrix(c(NA,1:4),nrow = 1),2, mean, na.rm = TRUE)


#### function link Clinical data to prediction data ####

# clinical





```