install.packages('tidyverse')
install.packages('spatstat')
install.packages('spdep')
install.packages('remotes')
remotes::install_github('akoyabio/tiff')
remotes::install_github('akoyabio/phenoptr', build_vignettes=TRUE)
# install.packages('zoo')
install.packages('RColorBrewer')
install.packages('reshape2')
install.packages('latex2exp')
