install.packages('tidyverse',repos="https://cloud.r-project.org")
install.packages('spatstat',repos="https://cloud.r-project.org")
install.packages('spdep',repos="https://cloud.r-project.org")
install.packages('remotes',repos="https://cloud.r-project.org")
remotes::install_github('akoyabio/tiff')
remotes::install_github('akoyabio/phenoptr', build_vignettes=TRUE)
# install.packages('zoo')
install.packages('RColorBrewer',repos="https://cloud.r-project.org")
install.packages('reshape2',repos="https://cloud.r-project.org")
install.packages('latex2exp',repos="https://cloud.r-project.org")
