---
title: "Main script Erik Vectra analysis"
output:
  html_document:
    toc: yes
---

```{r source files, echo=FALSE}
source('spatstat_vectra.R')

```

```{r RUN import files method Erik dependent on .Rdata, echo=FALSE, eval=FALSE}
######### RUN import files method Erik#########

paths <- list_cell_seg_files(
  "C:/Users/erikb/Documents/Thesis - Local/Data Marit voor Erik Bosch/Erik Bosch/Data complete phenotyping/HO105_Exported data tables"
)
paste("There are", length(paths), "different samples currently available.")

data = purrr::map_df(paths, read_cell_seg_data, pixels_per_micron = getOption("phenoptr.pixels.per.micron"))
paste("dimensions of the data is", dim(data)[1], "times", dim(data)[2]) # 1805834 197

data_with_distance = data %>%
  do(bind_cols(., find_nearest_distance(.)))
paste("dimensions of the data is", dim(data_filtered_with_distance)[1], "times", dim(data_filtered_with_distance)[2])

data_filtered = data %>% filter(Phenotype != "")
paste("dimensions of the data is", dim(data_filtered)[1], "times", dim(data_filtered)[2]) # 1805653 197

data_filtered_with_distance <- data_filtered %>%
  do(bind_cols(., find_nearest_distance(.)))
paste("dimensions of the data is", dim(data_filtered_with_distance)[1], "times", dim(data_filtered_with_distance)[2]) #1805653 217

```

```{r RUN preprocessing data and statistics, echo=FALSE}

# preprocessing data and statistics

# colors according to slides Marit and plot conventions
pheno_vector_absolut = c("CD163+PDL1-","CD163+PDL1+",
                         "CD3+CD8-PD1-", "CD3+CD8-PD1+", "CD3+CD8+PD1-", "CD3+CD8+PD1+",
                         "Other","Other PDL1+",
                         "PAX5+PDL1-", "PAX5+PDL1+", 
                         "")

colors_absolut = c("magenta", "brown", "red", "blue", "green", "yellow", "gray", "pink", "orange", "cyan", "gray")
names(colors_absolut) = pheno_vector_absolut

# convention to thresholding data

phenotype_simple = list(Macrophage = c("CD163+PDL1-","CD163+PDL1+"),
                      Tcells = c("CD3+CD8-PD1-", "CD3+CD8-PD1+", "CD3+CD8+PD1-", "CD3+CD8+PD1+"),
                      Tumors = c("PAX5+PDL1-", "PAX5+PDL1+"),
                      Others = c("Other", "Other PDL1+")
                      )

color_simple = c(Macrophage = "magenta", Tcells = "red", Tumors = "orange", Others = "gray")

```

```{r RUN do analyse on all samples, echo = TRUE, eval = TRUE}
# check for each image which pheotypes are missing for overview


source("spatstat_vectra.R")


# colors according to slides Marit and plot conventions - COMPLETE PHENOTYPING
phenotype_complete = c("CD163+PDL1-","CD163+PDL1+",
                       "CD3+CD8-PD1-", "CD3+CD8-PD1+", "CD3+CD8+PD1-", "CD3+CD8+PD1+",
                       "Other","Other PDL1+",
                       "PAX5+PDL1-", "PAX5+PDL1+",
                       "")

color_complete = c("magenta", "brown",
                   "red", "blue", "green", "yellow",
                   "gray", "pink",
                   "orange", "cyan",
                   "gray")
names(color_complete) = phenotype_complete

fig.prefix.complete = './complete'


# colors according to slides Marit and plot conventions - SIMPLE PHENOTYPING
phenotype_simple = list(Macrophage = c("CD163+PDL1-","CD163+PDL1+"),
                      Tcells = c("CD3+CD8-PD1-", "CD3+CD8-PD1+", "CD3+CD8+PD1-", "CD3+CD8+PD1+"),
                      Tumors = c("PAX5+PDL1-", "PAX5+PDL1+"),
                      Others = c("Other", "Other PDL1+")
                      )

color_simple = c(Macrophage = "magenta", Tcells = "red", Tumors = "orange", Others = "gray")

fig.prefix.simple = './simple'



# run for one sample name

samples_output = list()


paths <- list_cell_seg_files(
  "C:/Users/erikb/Documents/Thesis - Local/Data Marit voor Erik Bosch/Erik Bosch/Data complete phenotyping/HO105_Exported data tables"
)
paths <- "C:/Users/erikb/Documents/Thesis - Local/Data Marit voor Erik Bosch/Erik Bosch/Data complete phenotyping/HO105_Exported data tables/HO105-194_[16067,37856]_cell_seg_data.txt"

paste("There are", length(paths), "different samples currently available.")

samples_output = list()

# Plot variables and save

plotter_sample = TRUE
plotter_quadrat = TRUE
plotter_alltypes = TRUE

plotter_bools = list(plotter_sample, plotter_quadrat, plotter_alltypes)

r_vec = c(20)
# r_vec currently does not work well when given NULL see inside spatstat_vectra

# Characterstring of which option or NULL for all options
selected_options = list("G")


for (samplename_long in paths[1]){

  data = purrr::map_df(samplename_long, read_cell_seg_data, pixels_per_micron = getOption("phenoptr.pixels.per.micron"), remove_units = FALSE)
  
  samplename = str_remove(samplename_long,"C:/Users/erikb/Documents/Thesis - Local/Data Marit voor Erik Bosch/Erik Bosch/Data complete phenotyping/HO105_Exported data tables/")
  samplename = str_remove(samplename,"_cell_seg_data.txt")
  
  print(samplename)
  
  output = do_analyse(Intable = data, PhenoOrder = phenotype_simple, ColsOrder = color_simple,
                      XposCol = 'Cell X Position', YposCol = 'Cell Y Position', PhenoCol = 'Phenotype',
                      sample_name = samplename, plotter = plotter_bools, fig.prefix = fig.prefix.simple, fig.width = 720, fig.height = 720,
                      r_vec = r_vec, options = selected_options, envelope = TRUE)

  samples_output[[samplename]] = output
  # stop()
  
  pairwise_distances = output[[1]]
  counts_sample = output[[2]]
  Area_sample = output[[3]]
  density_sample = output[[4]]
  quadratcount_X2statistic = output[[5]]
  MED_min = output[[6]]
  MED = output[[7]]
  MAD_min = output[[8]]
  MAD = output[[9]]
  statistic_close_list = output[[10]]
  normalized_list = output[[11]]
  all_types_options_sample_name = output[[12]]
  
  
  
  # browser() # here for Erik to remember this method of debugging
}


```




```{r RUN data for extreme cases: HO105-194}
######### RUN data for extreme cases #########

source("spatstat_vectra.R")


# colors according to slides Marit and plot conventions
pheno_vector_absolut = c("CD163+PDL1-","CD163+PDL1+","CD3+CD8-PD1-", "CD3+CD8-PD1+", "CD3+CD8+PD1-", "CD3+CD8+PD1+","Other","Other PDL1+","PAX5+PDL1-", "PAX5+PDL1+")

colors_absolut = c("magenta", "brown", "red", "blue", "green", "yellow", "gray", "pink", "orange", "cyan")
names(colors_absolut) = pheno_vector_absolut


r_vec = c(20)
# r_vec currently does not work well when given NULL see inside spatstat_vectra

plotter_sample = TRUE
plotter_quadrat = TRUE
plotter_alltypes = FALSE

plotter_bools = c(plotter_sample, plotter_quadrat, plotter_alltypes)

selected_options = c("pcf","K")

# run for one sample name

samples_output = list()

# data from Marit: extreme cases

# HO105-194
samplename_path = "C:/Users/erikb/Documents/Thesis - Local/Data Marit voor Erik Bosch/Erik Bosch/Data complete phenotyping/HO105_Exported data tables/HO105-194_[16067,37856]_cell_seg_data.txt" # PD-L1 positive cluster + Tumor cluster

data = purrr::map_df(samplename_path, read_cell_seg_data, pixels_per_micron = getOption("phenoptr.pixels.per.micron"))
data_with_distance = data %>%
  do(bind_cols(., find_nearest_distance(.)))

samplename = str_remove(samplename_path,"C:/Users/erikb/Documents/Thesis - Local/Data Marit voor Erik Bosch/Erik Bosch/Data complete phenotyping/HO105_Exported data tables/")
samplename = str_remove(samplename,"_cell_seg_data.txt")

if (TRUE %in% plotter_bools){
  output_dir <- file.path("fig", samplename)
  
  if (!dir.exists(output_dir)){
    dir.create(output_dir)
  } else {
    print(paste("Directory",samplename, "already exists! Figures were overwritten."))
  }
}

output =  do_analyse(Intable = data_with_distance, PhenoOrder = pheno_vector_absolut, ColsOrder = colors_absolut, phenotype = NULL, plotter = plotter_bools, fig.prefix = output_dir, XposCol = 'Cell X Position', YposCol = 'Cell Y Position', PhenoCol = 'Phenotype', sample_name = samplename, r_vec = r_vec, options = selected_options, envelope_bool = TRUE)

samples_output[[samplename]] = output



samplename_path = "C:/Users/erikb/Documents/Thesis - Local/Data Marit voor Erik Bosch/Erik Bosch/Data complete phenotyping/HO105_Exported data tables/HO105-194_[15564,37856]_cell_seg_data.txt" # PD-L1 positive cluster + Tumor cluster

data = purrr::map_df(samplename_path, read_cell_seg_data, pixels_per_micron = getOption("phenoptr.pixels.per.micron"))
data_with_distance = data %>%
  do(bind_cols(., find_nearest_distance(.)))

samplename = str_remove(samplename_path,"C:/Users/erikb/Documents/Thesis - Local/Data Marit voor Erik Bosch/Erik Bosch/Data complete phenotyping/HO105_Exported data tables/")
samplename = str_remove(samplename,"_cell_seg_data.txt")

if (TRUE %in% plotter_bools){
  output_dir <- file.path("fig", samplename)
  
  if (!dir.exists(output_dir)){
    dir.create(output_dir)
  } else {
    print(paste("Directory",samplename, "already exists! Figures were overwritten."))
  }
}

output =  do_analyse(Intable = data_with_distance, PhenoOrder = pheno_vector_absolut, ColsOrder = colors_absolut, phenotype = NULL, plotter = plotter_bools, fig.prefix = output_dir, XposCol = 'Cell X Position', YposCol = 'Cell Y Position', PhenoCol = 'Phenotype', sample_name = samplename, r_vec = r_vec, options = selected_options, envelope_bool = TRUE)

samples_output[[samplename]] = output


samplename_path = "C:/Users/erikb/Documents/Thesis - Local/Data Marit voor Erik Bosch/Erik Bosch/Data complete phenotyping/HO105_Exported data tables/HO105-194_[16029,38205]_cell_seg_data.txt" # not clustered

data = purrr::map_df(samplename_path, read_cell_seg_data, pixels_per_micron = getOption("phenoptr.pixels.per.micron"))
data_with_distance = data %>%
  do(bind_cols(., find_nearest_distance(.)))

samplename = str_remove(samplename_path,"C:/Users/erikb/Documents/Thesis - Local/Data Marit voor Erik Bosch/Erik Bosch/Data complete phenotyping/HO105_Exported data tables/")
samplename = str_remove(samplename,"_cell_seg_data.txt")

if (TRUE %in% plotter_bools){
  output_dir <- file.path("fig", samplename)
  
  if (!dir.exists(output_dir)){
    dir.create(output_dir)
  } else {
    print(paste("Directory",samplename, "already exists! Figures were overwritten."))
  }
}

output =  do_analyse(Intable = data_with_distance, PhenoOrder = pheno_vector_absolut, ColsOrder = colors_absolut, phenotype = NULL, plotter = plotter_bools, fig.prefix = output_dir, XposCol = 'Cell X Position', YposCol = 'Cell Y Position', PhenoCol = 'Phenotype', sample_name = samplename, r_vec = r_vec, options = selected_options, envelope_bool = TRUE)

samples_output[[samplename]] = output

```

```{r RUN data for extreme cases: HO105-186}
# HO105-186

source("spatstat_vectra.R")


# colors according to slides Marit and plot conventions
pheno_vector_absolut = c("CD163+PDL1-","CD163+PDL1+","CD3+CD8-PD1-", "CD3+CD8-PD1+", "CD3+CD8+PD1-", "CD3+CD8+PD1+","Other","Other PDL1+","PAX5+PDL1-", "PAX5+PDL1+")

colors_absolut = c("magenta", "brown", "red", "blue", "green", "yellow", "gray", "pink", "orange", "cyan")
names(colors_absolut) = pheno_vector_absolut


r_vec = c(20)
# r_vec currently does not work well when given NULL see inside spatstat_vectra

plotter_sample = TRUE
plotter_quadrat = TRUE
plotter_alltypes = FALSE

plotter_bools = c(plotter_sample, plotter_quadrat, plotter_alltypes)

selected_options = NULL

# run for one sample name

samples_output = list()

# data from Marit: extreme cases



samplename_path = "C:/Users/erikb/Documents/Thesis - Local/Data Marit voor Erik Bosch/Erik Bosch/Data complete phenotyping/HO105_Exported data tables/HO105-186_[18941,59427]_cell_seg_data.txt" # PD-L1 positive cluster + Tumor cluster

data = purrr::map_df(samplename_path, read_cell_seg_data, pixels_per_micron = getOption("phenoptr.pixels.per.micron"))
data_with_distance = data %>%
  do(bind_cols(., find_nearest_distance(.)))

samplename = str_remove(samplename_path,"C:/Users/erikb/Documents/Thesis - Local/Data Marit voor Erik Bosch/Erik Bosch/Data complete phenotyping/HO105_Exported data tables/")
samplename = str_remove(samplename,"_cell_seg_data.txt")

if (TRUE %in% plotter_bools){
  output_dir <- file.path("fig", samplename)
  
  if (!dir.exists(output_dir)){
    dir.create(output_dir)
  } else {
    print(paste("Directory",samplename, "already exists! Figures were overwritten."))
  }
}

output =  do_analyse(Intable = data_with_distance, PhenoOrder = pheno_vector_absolut, ColsOrder = colors_absolut, phenotype = NULL, plotter = plotter_bools, fig.prefix = output_dir, XposCol = 'Cell X Position', YposCol = 'Cell Y Position', PhenoCol = 'Phenotype', sample_name = samplename, r_vec = r_vec, options = selected_options, envelope_bool = TRUE)

samples_output[[samplename]] = output



samplename_path = "C:/Users/erikb/Documents/Thesis - Local/Data Marit voor Erik Bosch/Erik Bosch/Data complete phenotyping/HO105_Exported data tables/HO105-186_[18837,59867]_cell_seg_data.txt" # PD-L1 positive cluster + Tumor cluster

data = purrr::map_df(samplename_path, read_cell_seg_data, pixels_per_micron = getOption("phenoptr.pixels.per.micron"))
data_with_distance = data %>%
  do(bind_cols(., find_nearest_distance(.)))

samplename = str_remove(samplename_path,"C:/Users/erikb/Documents/Thesis - Local/Data Marit voor Erik Bosch/Erik Bosch/Data complete phenotyping/HO105_Exported data tables/")
samplename = str_remove(samplename,"_cell_seg_data.txt")

if (TRUE %in% plotter_bools){
  output_dir <- file.path("fig", samplename)
  
  if (!dir.exists(output_dir)){
    dir.create(output_dir)
  } else {
    print(paste("Directory",samplename, "already exists! Figures were overwritten."))
  }
}

output =  do_analyse(Intable = data_with_distance, PhenoOrder = pheno_vector_absolut, ColsOrder = colors_absolut, phenotype = NULL, plotter = plotter_bools, fig.prefix = output_dir, XposCol = 'Cell X Position', YposCol = 'Cell Y Position', PhenoCol = 'Phenotype', sample_name = samplename, r_vec = r_vec, options = selected_options, envelope_bool = TRUE)

samples_output[[samplename]] = output



samplename_path = "C:/Users/erikb/Documents/Thesis - Local/Data Marit voor Erik Bosch/Erik Bosch/Data complete phenotyping/HO105_Exported data tables/HO105-186_[18127,59130]_cell_seg_data.txt" # PD-L1 positive cluster + Tumor cluster

data = purrr::map_df(samplename_path, read_cell_seg_data, pixels_per_micron = getOption("phenoptr.pixels.per.micron"))
data_with_distance = data %>%
  do(bind_cols(., find_nearest_distance(.)))

samplename = str_remove(samplename_path,"C:/Users/erikb/Documents/Thesis - Local/Data Marit voor Erik Bosch/Erik Bosch/Data complete phenotyping/HO105_Exported data tables/")
samplename = str_remove(samplename,"_cell_seg_data.txt")

if (TRUE %in% plotter_bools){
  output_dir <- file.path("fig", samplename)
  
  if (!dir.exists(output_dir)){
    dir.create(output_dir)
  } else {
    print(paste("Directory",samplename, "already exists! Figures were overwritten."))
  }
}

output =  do_analyse(Intable = data_with_distance, PhenoOrder = pheno_vector_absolut, ColsOrder = colors_absolut, phenotype = NULL, plotter = plotter_bools, fig.prefix = output_dir, XposCol = 'Cell X Position', YposCol = 'Cell Y Position', PhenoCol = 'Phenotype', sample_name = samplename, r_vec = r_vec, options = selected_options, envelope_bool = TRUE)

samples_output[[samplename]] = output



samplename_path = "C:/Users/erikb/Documents/Thesis - Local/Data Marit voor Erik Bosch/Erik Bosch/Data complete phenotyping/HO105_Exported data tables/HO105-186_[14661,55645]_cell_seg_data.txt" # PD-L1 positive cluster + Tumor cluster

data = purrr::map_df(samplename_path, read_cell_seg_data, pixels_per_micron = getOption("phenoptr.pixels.per.micron"))
data_with_distance = data %>%
  do(bind_cols(., find_nearest_distance(.)))

samplename = str_remove(samplename_path,"C:/Users/erikb/Documents/Thesis - Local/Data Marit voor Erik Bosch/Erik Bosch/Data complete phenotyping/HO105_Exported data tables/")
samplename = str_remove(samplename,"_cell_seg_data.txt")

if (TRUE %in% plotter_bools){
  output_dir <- file.path("fig", samplename)
  
  if (!dir.exists(output_dir)){
    dir.create(output_dir)
  } else {
    print(paste("Directory",samplename, "already exists! Figures were overwritten."))
  }
}

output =  do_analyse(Intable = data_with_distance, PhenoOrder = pheno_vector_absolut, ColsOrder = colors_absolut, phenotype = NULL, plotter = plotter_bools, fig.prefix = output_dir, XposCol = 'Cell X Position', YposCol = 'Cell Y Position', PhenoCol = 'Phenotype', sample_name = samplename, r_vec = r_vec, options = selected_options, envelope_bool = TRUE)

samples_output[[samplename]] = output



samplename_path = "C:/Users/erikb/Documents/Thesis - Local/Data Marit voor Erik Bosch/Erik Bosch/Data complete phenotyping/HO105_Exported data tables/HO105-186_[14121,55575]_cell_seg_data.txt" # PD-L1 positive cluster + Tumor cluster

data = purrr::map_df(samplename_path, read_cell_seg_data, pixels_per_micron = getOption("phenoptr.pixels.per.micron"))
data_with_distance = data %>%
  do(bind_cols(., find_nearest_distance(.)))

samplename = str_remove(samplename_path,"C:/Users/erikb/Documents/Thesis - Local/Data Marit voor Erik Bosch/Erik Bosch/Data complete phenotyping/HO105_Exported data tables/")
samplename = str_remove(samplename,"_cell_seg_data.txt")

if (TRUE %in% plotter_bools){
  output_dir <- file.path("fig", samplename)
  
  if (!dir.exists(output_dir)){
    dir.create(output_dir)
  } else {
    print(paste("Directory",samplename, "already exists! Figures were overwritten."))
  }
}

output =  do_analyse(Intable = data_with_distance, PhenoOrder = pheno_vector_absolut, ColsOrder = colors_absolut, phenotype = NULL, plotter = plotter_bools, fig.prefix = output_dir, XposCol = 'Cell X Position', YposCol = 'Cell Y Position', PhenoCol = 'Phenotype', sample_name = samplename, r_vec = r_vec, options = selected_options, envelope_bool = TRUE)

samples_output[[samplename]] = output

view(samples_output)
```

```{r RUN data for extreme cases: HO105-101}
# HO105-101
source("spatstat_vectra.R")


# colors according to slides Marit and plot conventions
pheno_vector_absolut = c("CD163+PDL1-","CD163+PDL1+","CD3+CD8-PD1-", "CD3+CD8-PD1+", "CD3+CD8+PD1-", "CD3+CD8+PD1+","Other","Other PDL1+","PAX5+PDL1-", "PAX5+PDL1+")

colors_absolut = c("magenta", "brown", "red", "blue", "green", "yellow", "gray", "pink", "orange", "cyan")
names(colors_absolut) = pheno_vector_absolut


r_vec = c(20)
# r_vec currently does not work well when given NULL see inside spatstat_vectra

plotter_sample = TRUE
plotter_quadrat = TRUE
plotter_alltypes = TRUE

plotter_bools = c(plotter_sample, plotter_quadrat, plotter_alltypes)

selected_options = NULL

# run for one sample name

samples_output = list()


samplename_path = "C:/Users/erikb/Documents/Thesis - Local/Data Marit voor Erik Bosch/Erik Bosch/Data complete phenotyping/HO105_Exported data tables/HO105-101_[9072,46519]_cell_seg_data.txt" # Spreadout Tumor

data = purrr::map_df(samplename_path, read_cell_seg_data, pixels_per_micron = getOption("phenoptr.pixels.per.micron"))
data_with_distance = data %>%
  do(bind_cols(., find_nearest_distance(.)))

samplename = str_remove(samplename_path,"C:/Users/erikb/Documents/Thesis - Local/Data Marit voor Erik Bosch/Erik Bosch/Data complete phenotyping/HO105_Exported data tables/")
samplename = str_remove(samplename,"_cell_seg_data.txt")

if (TRUE %in% plotter_bools){
  output_dir <- file.path("fig", samplename)
  
  if (!dir.exists(output_dir)){
    dir.create(output_dir)
  } else {
    print(paste("Directory",samplename, "already exists! Figures were overwritten."))
  }
}

output =  do_analyse(Intable = data_with_distance, PhenoOrder = pheno_vector_absolut, ColsOrder = colors_absolut, phenotype = NULL, plotter = plotter_bools, fig.prefix = output_dir, XposCol = 'Cell X Position', YposCol = 'Cell Y Position', PhenoCol = 'Phenotype', sample_name = samplename, r_vec = r_vec, options = selected_options, envelope_bool = TRUE)

samples_output[[samplename]] = output

view(samples_output)
```

```{r RUN data for extreme cases: HO105-150}
# HO105-150
source("spatstat_vectra.R")


# colors according to slides Marit and plot conventions
pheno_vector_absolut = c("CD163+PDL1-","CD163+PDL1+","CD3+CD8-PD1-", "CD3+CD8-PD1+", "CD3+CD8+PD1-", "CD3+CD8+PD1+","Other","Other PDL1+","PAX5+PDL1-", "PAX5+PDL1+")

colors_absolut = c("magenta", "brown", "red", "blue", "green", "yellow", "gray", "pink", "orange", "cyan")
names(colors_absolut) = pheno_vector_absolut


r_vec = c(20)
# r_vec currently does not work well when given NULL see inside spatstat_vectra

plotter_sample = TRUE
plotter_quadrat = TRUE
plotter_alltypes = FALSE

plotter_bools = c(plotter_sample, plotter_quadrat, plotter_alltypes)

selected_options = NULL

# run for one sample name

samples_output = list()


samplename_path = "C:/Users/erikb/Documents/Thesis - Local/Data Marit voor Erik Bosch/Erik Bosch/Data complete phenotyping/HO105_Exported data tables/HO105-150_[13112,45808]_cell_seg_data.txt" # Spreadout Tumor

data = purrr::map_df(samplename_path, read_cell_seg_data, pixels_per_micron = getOption("phenoptr.pixels.per.micron"))
data_with_distance = data %>%
  do(bind_cols(., find_nearest_distance(.)))

samplename = str_remove(samplename_path,"C:/Users/erikb/Documents/Thesis - Local/Data Marit voor Erik Bosch/Erik Bosch/Data complete phenotyping/HO105_Exported data tables/")
samplename = str_remove(samplename,"_cell_seg_data.txt")

if (TRUE %in% plotter_bools){
  output_dir <- file.path("fig", samplename)
  
  if (!dir.exists(output_dir)){
    dir.create(output_dir)
  } else {
    print(paste("Directory",samplename, "already exists! Figures were overwritten."))
  }
}

output =  do_analyse(Intable = data_with_distance, PhenoOrder = pheno_vector_absolut, ColsOrder = colors_absolut, phenotype = NULL, plotter = plotter_bools, fig.prefix = output_dir, XposCol = 'Cell X Position', YposCol = 'Cell Y Position', PhenoCol = 'Phenotype', sample_name = samplename, r_vec = r_vec, options = selected_options, envelope_bool = TRUE)

samples_output[[samplename]] = output


# view(samples_output)
```

```{r RUN data for extreme cases: HO105-120}
# HO105-120
source("spatstat_vectra.R")


# colors according to slides Marit and plot conventions
pheno_vector_absolut = c("CD163+PDL1-","CD163+PDL1+","CD3+CD8-PD1-", "CD3+CD8-PD1+", "CD3+CD8+PD1-", "CD3+CD8+PD1+","Other","Other PDL1+","PAX5+PDL1-", "PAX5+PDL1+")

colors_absolut = c("magenta", "brown", "red", "blue", "green", "yellow", "gray", "pink", "orange", "cyan")
names(colors_absolut) = pheno_vector_absolut


r_vec = c(20)
# r_vec currently does not work well when given NULL see inside spatstat_vectra

plotter_sample = TRUE
plotter_quadrat = TRUE
plotter_alltypes = FALSE

plotter_bools = c(plotter_sample, plotter_quadrat, plotter_alltypes)

# run for one sample name

samples_output = list()

samplename_path = "C:/Users/erikb/Documents/Thesis - Local/Data Marit voor Erik Bosch/Erik Bosch/Data complete phenotyping/HO105_Exported data tables/HO105-120_[5524,47985]_cell_seg_data.txt" # Spreadout Tumor

data = purrr::map_df(samplename_path, read_cell_seg_data, pixels_per_micron = getOption("phenoptr.pixels.per.micron"))
data_with_distance = data %>%
  do(bind_cols(., find_nearest_distance(.)))

samplename = str_remove(samplename_path,"C:/Users/erikb/Documents/Thesis - Local/Data Marit voor Erik Bosch/Erik Bosch/Data complete phenotyping/HO105_Exported data tables/")
samplename = str_remove(samplename,"_cell_seg_data.txt")

if (TRUE %in% plotter_bools){
  output_dir <- file.path("fig", samplename)
  
  if (!dir.exists(output_dir)){
    dir.create(output_dir)
  } else {
    print(paste("Directory",samplename, "already exists! Figures were overwritten."))
  }
}

output =  do_analyse(Intable = data_with_distance, PhenoOrder = pheno_vector_absolut, ColsOrder = colors_absolut, phenotype = NULL, plotter = plotter_bools, fig.prefix = output_dir, XposCol = 'Cell X Position', YposCol = 'Cell Y Position', PhenoCol = 'Phenotype', sample_name = samplename, r_vec = r_vec, options = selected_options, envelope_bool = TRUE)

samples_output[[samplename]] = output


view(samples_output)
```

```{r RUN data for extreme cases: HO105-107}
# HO105-107
source("spatstat_vectra.R")


# colors according to slides Marit and plot conventions
pheno_vector_absolut = c("CD163+PDL1-","CD163+PDL1+","CD3+CD8-PD1-", "CD3+CD8-PD1+", "CD3+CD8+PD1-", "CD3+CD8+PD1+","Other","Other PDL1+","PAX5+PDL1-", "PAX5+PDL1+")

colors_absolut = c("magenta", "brown", "red", "blue", "green", "yellow", "gray", "pink", "orange", "cyan")
names(colors_absolut) = pheno_vector_absolut
print(colors_absolut)

r_vec = c(20)
# r_vec currently does not work well when given NULL see inside spatstat_vectra

plotter_sample = TRUE
plotter_quadrat = TRUE
plotter_alltypes = FALSE

plotter_bools = c(plotter_sample, plotter_quadrat, plotter_alltypes)

selected_options = NULL

# run for one sample name

samples_output = list()

samplename_path = "C:/Users/erikb/Documents/Thesis - Local/Data Marit voor Erik Bosch/Erik Bosch/Data complete phenotyping/HO105_Exported data tables/HO105-107_[11070,34907]_cell_seg_data.txt" # T-cell cluster

data = purrr::map_df(samplename_path, read_cell_seg_data, pixels_per_micron = getOption("phenoptr.pixels.per.micron"))
data_with_distance = data %>%
  do(bind_cols(., find_nearest_distance(.)))

samplename = str_remove(samplename_path,"C:/Users/erikb/Documents/Thesis - Local/Data Marit voor Erik Bosch/Erik Bosch/Data complete phenotyping/HO105_Exported data tables/")
samplename = str_remove(samplename,"_cell_seg_data.txt")

if (TRUE %in% plotter_bools){
  output_dir <- file.path("fig", samplename)
  print(output_dir)
  if (!dir.exists(output_dir)){
    dir.create(output_dir)
  } else {
    print(paste("Directory",samplename, "already exists! Figures were overwritten."))
  }
}

output =  do_analyse(Intable = data_with_distance, PhenoOrder = pheno_vector_absolut, ColsOrder = colors_absolut, phenotype = NULL, plotter = plotter_bools, fig.prefix = output_dir, XposCol = 'Cell X Position', YposCol = 'Cell Y Position', PhenoCol = 'Phenotype', sample_name = samplename, r_vec = r_vec, options = selected_options, envelope_bool = TRUE)

samples_output[[samplename]] = output


view(samples_output)
```

```{r RUN data for extreme cases: HO105-171_3}
# HO105-171_3
source("spatstat_vectra.R")


# colors according to slides Marit and plot conventions
pheno_vector_absolut = c("CD163+PDL1-","CD163+PDL1+","CD3+CD8-PD1-", "CD3+CD8-PD1+", "CD3+CD8+PD1-", "CD3+CD8+PD1+","Other","Other PDL1+","PAX5+PDL1-", "PAX5+PDL1+")

colors_absolut = c("magenta", "brown", "red", "blue", "green", "yellow", "gray", "pink", "orange", "cyan")
names(colors_absolut) = pheno_vector_absolut

r_vec = c(20)
# r_vec currently does not work well when given NULL see inside spatstat_vectra

plotter_sample = TRUE
plotter_quadrat = TRUE
plotter_alltypes = TRUE

plotter_bools = c(plotter_sample, plotter_quadrat, plotter_alltypes)

selected_options = "K"

# run for one sample name

samples_output = list()


samplename_path = "C:/Users/erikb/Documents/Thesis - Local/Data Marit voor Erik Bosch/Erik Bosch/Data complete phenotyping/HO105_Exported data tables/HO105-171_3_[6297,46984]_cell_seg_data.txt" # T-cell cluster surrounded by Other

data = purrr::map_df(samplename_path, read_cell_seg_data, pixels_per_micron = getOption("phenoptr.pixels.per.micron"))
data_with_distance = data %>%
  do(bind_cols(., find_nearest_distance(.)))

samplename = str_remove(samplename_path,"C:/Users/erikb/Documents/Thesis - Local/Data Marit voor Erik Bosch/Erik Bosch/Data complete phenotyping/HO105_Exported data tables/")
samplename = str_remove(samplename,"_cell_seg_data.txt")

if (TRUE %in% plotter_bools){
  output_dir <- file.path("fig", samplename)
  
  if (!dir.exists(output_dir)){
    dir.create(output_dir)
  } else {
    print(paste("Directory",samplename, "already exists! Figures were overwritten."))
  }
}

output =  do_analyse(Intable = data_with_distance, PhenoOrder = pheno_vector_absolut, ColsOrder = colors_absolut, phenotype = NULL, plotter = plotter_bools, fig.prefix = output_dir, XposCol = 'Cell X Position', YposCol = 'Cell Y Position', PhenoCol = 'Phenotype', sample_name = samplename, r_vec = r_vec, options = selected_options, envelope_bool = TRUE)

samples_output[[samplename]] = output



samplename_path = "C:/Users/erikb/Documents/Thesis - Local/Data Marit voor Erik Bosch/Erik Bosch/Data complete phenotyping/HO105_Exported data tables/HO105-171_3_[12870,46254]_cell_seg_data.txt" # T-cell cluster surrounded by Other

data = purrr::map_df(samplename_path, read_cell_seg_data, pixels_per_micron = getOption("phenoptr.pixels.per.micron"))
data_with_distance = data %>%
  do(bind_cols(., find_nearest_distance(.)))

samplename = str_remove(samplename_path,"C:/Users/erikb/Documents/Thesis - Local/Data Marit voor Erik Bosch/Erik Bosch/Data complete phenotyping/HO105_Exported data tables/")
samplename = str_remove(samplename,"_cell_seg_data.txt")

output =  do_analyse(Intable = data_with_distance, PhenoOrder = pheno_vector_absolut, ColsOrder = colors_absolut, phenotype = NULL, plotter = plotter_bools, fig.prefix = output_dir, XposCol = 'Cell X Position', YposCol = 'Cell Y Position', PhenoCol = 'Phenotype', sample_name = samplename, r_vec = r_vec, options = selected_options, envelope_bool = TRUE)

samples_output[[samplename]] = output


view(samples_output)
```

